steps:
# Build and deploy frontend
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/durable-sound-440422-u5/vola-frontend', './frontend']
  dir: '.'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/durable-sound-440422-u5/vola-frontend']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'vola-frontend'
  - '--image'
  - 'gcr.io/durable-sound-440422-u5/vola-frontend'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'VITE_API_URL=https://your-existing-backend-url.run.app'  # Replace with your actual backend URL

images:
- 'gcr.io/durable-sound-440422-u5/vola-frontend'
